#!/usr/bin/env sh
#=========================================================================
# Author: Gaetan (gaetan@ictpourtous.com) - Twitter: @GaetanICT
# Creation: Fri 17 Sep 2021 08:06:28
# Last modified: Fri 17 Sep 2021 08:08:05
# Version: 1.0
#
# Description: export ST buffer to a text editor. Useful to record the screen
#=========================================================================

[ -z "$EDITOR" ] && EDITOR=vim
tmpfile=$(mktemp /tmp/st-edit.XXXXXX)
trap  'rm "$tmpfile"' 0 1 15
cat > "$tmpfile"
st -e "$EDITOR" "$tmpfile"
